apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: application
spec:
  selector:
    app: flask-app
  ports:
    - name: app-endpoint
      port: 5000
      targetPort: api
      nodePort: 30000 # expose to localhost
  type: NodePort # expose to localhost