stages:
  - test
  - install
  - build

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

test_tox:
  stage: test
  image: painless/tox
  script:
    - tox

install_deps_api:
  stage: install
  image: tampakrap/venv:3.7
  before_script:
    - virtualenv .venv
    - source .venv/bin/activate
  script:
    - pip install -r requirements.txt
  cache:
    paths:
      - .cache/pip
      - .venv/

build_api:
  stage: build
  image: docker
  services:
    - docker:19.03.12-dind
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}/api .
    - docker login -u $REGISTRY_USER -p $REGISTRY_TOKEN $CI_REGISTRY
    - docker push ${CI_REGISTRY_IMAGE}/api
  cache:
    paths:
      - .cache/pip
      - .venv/

build_mongodb:
  stage: build
  image: docker
  services:
    - docker:19.03.12-dind
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}/mongodb -f data/Dockerfile .
    - docker login -u $REGISTRY_USER -p $REGISTRY_TOKEN $CI_REGISTRY
    - docker push ${CI_REGISTRY_IMAGE}/mongodb
