FROM python:3

LABEL maintainer "mrsystemfox@example.com" 

ENV PROJECT_DIR=/app

WORKDIR $PROJECT_DIR

COPY src $PROJECT_DIR/src

COPY requirements.txt $PROJECT_DIR

RUN pip install -r requirements.txt

COPY app.py /app

EXPOSE 8080

HEALTHCHECK CMD curl --fail localhost:8080/api/v1/restaurant || exit 

CMD ["python", "app.py"]
