FROM mongo:4.4

# Maintainer of the Dockerfile
LABEL maintainer "Borja Lopez <borja.lopez@xxxx.com>"

# Custom user creation
COPY scripts/mongo-import.sh /docker-entrypoint-initdb.d/
COPY data/restaurant.json /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/mongo-import.sh
