version: '3'
services:
  mongodb:
    image: mongo:6.0.8
    container_name: mongodb
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeme

  mongo_seed:
    image: mongo_seed
    container_name: seed
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      ROOT_USERNAME: root
      ROOT_PASSWORD: changeme
      AUTH_DB: admin
      APP_DB: intelygenz_db
      MONGO_USERNAME: intelygenz
      MONGO_USERNAME_PASS: intelygenz_changeme
    depends_on:
      - mongodb