# Use  mongo:4.2 as base image
FROM mongo:4.2

# Maintainer of the Dockerfile
LABEL maintainer "Alejandro Aceituna Cano - IGZ Devops Team <devops@intelygenz.com>"

# Environment variables
ENV TZ=Europe/Madrid

#  Set the time zone
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Custom user creation
COPY files/mongo-import.sh /docker-entrypoint-initdb.d/
COPY data/restaurant.json /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/mongo-import.sh

# Database seeder
#RUN mongoimport --username igz --password password --db restaurant --collection restaurant --drop --file data/restaurant.json
