# Use  mongo:4.2 as base image
FROM mongo:4.2

# Maintainer of the Dockerfile
LABEL maintainer "Alejandro Aceituna Cano - IGZ Devops Team <devops@intelygenz.com>"

# Environment variables
ENV MONGO_NON_ROOT_USERNAME igz \
    MONGO_NON_ROOT_PASSWORD password \
    MONGO_INITDB_DATABASE restaurant \
    MONGO_INITDB_ROOT_USERNAME root \
    MONGO_INITDB_ROOT_PASSWORD supersecret \
    ENV TZ=Europe/Madrid

#  Set the time zone
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Custom user creation
COPY files/custom-user.sh /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/custom-user.sh

# Database seeder
RUN mongoimport --username igz --password password --db restaurant --collection restaurant --drop --file data/restaurant.json