FROM mongo:4.4

# Maintainer of the Dockerfile
LABEL maintainer "Borja Lopez <borja.lopez@xxxx.com>"

# Custom user creation
COPY scripts/mongo-user.sh /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/mongo-user.sh
