{{- if and (.Values.serviceAccount.enabled) (not .Values.serviceAccount.name) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "mongodb.labels" . | indent 4 }}
  name: {{ template "mongodb.fullname" . }}
{{- end }}