{{- if (include "mongodb.createConfigmap" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mongodb.configmapName" . }}
  labels:
{{ include "mongodb.labels" . | indent 4 }}
data:
{{ (.Files.Glob "config/*").AsConfig | indent 2 }}
{{- end -}}