{{- if and (include "mongodb.createUserSecret" .) .Release.IsInstall }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.secretUserName" . }}
  annotations:
   "helm.sh/resource-policy": keep
  labels:
{{ include "mongodb.labels" . | indent 4 }}
type: Opaque
data:
  app-password: {{ include "mongodb.userPassword" . | b64enc | quote }}
{{- end -}}
