{{- if and (include "mongodb.createRootSecret" .) .Release.IsInstall }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.secretRootName" . }}
  annotations:
   "helm.sh/resource-policy": keep
  labels:
{{ include "mongodb.labels" . | indent 4 }}
type: Opaque
data:
  mongo-password: {{ include "mongodb.rootPassword" . | b64enc | quote }}
{{- end -}}