apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-mongodb-trdc
  namespace: default
data:
  MONGO_INITDB_ROOT_USERNAME: mongoadmin
  MONGO_INITDB_ROOT_PASSWORD: mongopassword
  MONGO_INITDB_DATABASE: main