apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongodb-trdc-service
  name: mongodb-trdc-service
  namespace: default
spec:
  ports:
    - port: 27017
  selector:
    app: mongodb-trdc
  type: ClusterIP