version: '3'
services:
  app:
    container_name: app
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    network_mode: "host"
    environment:
      MONGO_URI: mongodb://mongoadmin:mongopassword@127.0.0.1:27017/main
      DEBUG: "True"
    depends_on:
      - mongo
    ports:
      - "8080:8080"
  mongo:
    container_name: mongodb
    build:
      context: ../
      dockerfile: ./docker/mongodb/Dockerfile
    network_mode: "host"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
      MONGO_INITDB_DATABASE: main