apiVersion: v1
kind: Service
metadata:
  labels:
    name: app-trdc-service
  name: app-trdc-service
  namespace: default
spec:
  ports:
    - port: 8080
  selector:
    app: app-trdc
  type: ClusterIP