apiVersion: v1
kind: Service
metadata:
  annotations:
    app: mongodb
  creationTimestamp: null
  labels:
    app: mongodb
  name: mongodb-svc
spec:
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  selector:
    app: mongodb
status:
  loadBalancer: {}
