apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==
  MONGO_INITDB_ROOT_PASSWORD: cGFzcw==
  APP_DB_USERNAME: YXBwX3Vzcg==
  APP_DB_PASSWORD: YXBwX3B3ZA==