apiVersion: v1
kind: Service
metadata:
  annotations:
    app: webapp
  creationTimestamp: null
  labels:
    app: webapp
  name: webapp-svc
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: webapp
status:
  loadBalancer: {}
