FROM mongo:4.4.10

COPY ./config_scripts/mongo-import.sh /docker-entrypoint-initdb.d/
COPY ./data/restaurant.json /docker-entrypoint-initdb.d/

RUN chmod +x /docker-entrypoint-initdb.d/mongo-import.sh

CMD [ "bash", "/docker-entrypoint-initdb.d/mongo-import.sh" ]